# Generated by Django 5.1.2 on 2024-11-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('list_1', models.TextField(max_length=1000)),
                ('list_2', models.TextField(max_length=1000)),
                ('list_3', models.TextField(max_length=1000)),
                ('explanation', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('button', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('full_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('profile_pic', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('explanation', models.TextField(max_length=1000)),
                ('discussion', models.TextField(max_length=1000)),
                ('list_1', models.TextField(max_length=1000)),
                ('list_2', models.TextField(max_length=1000)),
                ('list_3', models.TextField(max_length=1000)),
                ('list_4', models.TextField(max_length=1000)),
                ('conclusion', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('button', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('image_1', models.ImageField(upload_to='images/')),
                ('image_2', models.ImageField(upload_to='images/')),
                ('image_3', models.ImageField(upload_to='images/')),
                ('image_4', models.ImageField(upload_to='images/')),
                ('image_5', models.ImageField(upload_to='images/')),
                ('image_6', models.ImageField(upload_to='images/')),
                ('image_7', models.ImageField(upload_to='images/')),
                ('image_8', models.ImageField(upload_to='images/')),
                ('image_9', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('list_1', models.TextField(max_length=1000)),
                ('list_2', models.TextField(max_length=1000)),
                ('list_3', models.TextField(max_length=1000)),
                ('list_4', models.TextField(max_length=1000)),
                ('list_5', models.TextField(max_length=1000)),
                ('list_6', models.TextField(max_length=1000)),
                ('button', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('twitter_url', models.URLField(max_length=1000)),
                ('facebook_url', models.URLField(max_length=1000)),
                ('instagram_url', models.URLField(max_length=1000)),
                ('linkedin_url', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('full_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
            ],
        ),
    ]
